# Generated by Django 4.0.4 on 2022-06-18 06:23

from django.db import migrations, models
import djangojokes.storage_backends
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_applicant_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, help_text='PDFs only', storage=djangojokes.storage_backends.PrivateMediaStorage(), upload_to='resumes', validators=[jobs.models.validate_pdf]),
        ),
    ]
