# Generated by Django 4.0.4 on 2022-06-21 22:54

from django.db import migrations, models
import jobs.models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_applicant_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='available_days',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=private_storage.fields.PrivateFileField(blank=True, help_text='PDFs only', storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='resumes', validators=[jobs.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='start_date',
            field=models.DateField(help_text='The earliest date you can start working.', validators=[jobs.models.validate_future_date]),
        ),
    ]
