# Generated by Django 4.0.4 on 2022-06-21 23:07

from django.db import migrations, models
import djangojokes.storage_backends
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_applicant_available_days_alter_applicant_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, help_text='PDFs only', storage=djangojokes.storage_backends.PrivateMediaStorage(), upload_to='resumes', validators=[jobs.models.validate_pdf]),
        ),
    ]
